baseURL = "https://kizokumaru.github.io/familydashboard/"
languageCode = "es"
title = "Dashboard"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "Contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = 0